# Replace the text below to customize your site
site_name: Maxime Verstraeten - FabAcademy 2021
site_description: My FabAcademy Documentation Website
site_url: http://fabacademy.org/2021/labs/ulb/students/maxime-verstraeten
repo_url: https://gitlab.fabcloud.org/academany/fabacademy/2021/labs/ulb/students/maxime-verstraeten.git
google_analytics:
    - G-W95SS0KBVE
    - auto
site_author: Maxime Verstraeten
docs_dir: docs
site_dir: _site
copyright: Creative Commons Attribution Non Commercial - Copyright &copy; 2021 Maxime Verstraeten
edit_uri: "" #comment to get the edit button on each page


nav:
    - Home: index.md
    - Final Project: './project/final-project.md'
    - My FabAcademy Journey:
        - './modules/index.md'
        - './modules/module00.md'
        - './modules/module01.md'
    - About:
        - License: './about/license.md'
        - Release Notes: './about/release-notes.md'
        - Student Agreement: './about/agreement.md'

    #- external Site: https://www.mkdocs.org/user-guide/configuration/

theme:
    name: material    #using material UI framework
    palette:
        scheme: slate #slate/default
        primary: deep purple
        accent: deep orange
    font:
        text: Noto Sans JP
    language: en
    favicon: img/logo/favicon.svg
    icon:
        logo: material/library
        repo: fontawesome/brands/gitlab
    features:
        - navigation.instant
        #- navigation.tabs
        #- toc.integrate
        - header.autohide
    extra:
        include_sidebar: true

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link : https://www.linkedin.com/in/maverstr/
        - icon: fontawesome/brands/github
          link : https://github.com/maverstr
        - icon: fontawesome/solid/paper-plane
          link: mailto:<maxime.verstraeten@ulb.be>

markdown_extensions:
    - meta #page-specific context
    - admonition #pretty notes
    - pymdownx.superfences #nested code blocks
    - pymdownx.highlight: #code blocks syntax highlighting
        linenums: true
        guess_lang: true
    - pymdownx.inlinehilite #inline code blocks highlighting
    - pymdownx.keys #maj, control, windows, ... key icons
    - pymdownx.caret #enables nice sub- and superscript
    - pymdownx.mark
    - pymdownx.tilde
    - abbr #allwos to add text that appears when hovered: the test here *[test]: this is a test
    - toc:
        permalink: true #insert an anchor
    - smarty #converts ASCII dashes, quotes and ellipses to their HTML equivalents
    - sane_lists #alter the behavior for lists to be less surprising...
    - attr_list #can add html attributes to markdown elements
    - pymdownx.emoji: #add icons and emoji
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - git-revision-date-localized: #adds a revision or build time info at the bottom of each page
      type: datetime
      fallback_to_build_date: true
  - search

extra_css:
  - css/extra.css #override theme font, style, colors, ...
